export const LANG_VI_NAME = 'vi';
export const LANG_VI_TRANS = {
    'Abandon': 'Rời bỏ',
    'Abandoned': 'Rời bỏ',
    'Are you sure to abandon the game?': 'Bạn có chắc chắn muốn bỏ game?',
    'You can use voice chat with the other player.': 'Bạn có thể nói chuyện với người chơi.',
    'wants to use voice chat with you.': 'muốn nói chuyện với bạn.',
    'Do you want to accept?': 'Bạn có muốn chấp nhận',
    'Yes': 'Có',
    'No': 'Không',
    'Cancel': 'Huỷ bỏ',
    'Connecting': 'Đang kết nối',
    'Connected': 'Đã kết nối',
    'Could not find any game with the provided passcode.': 'Không tìm thấy game nào với mã được nhập.',
    'Create a private game': 'Tạo game riêng',
    'Enter Passcode to join the private game.': 'Nhập mã để tham gia game riêng.',
    'Disconnected': 'Rớt kết nối',
    'Failed': 'Thất bại',
    'for another player to join your game.': 'Người chơi khác tham gia với bạn.',
    'for the other player to reconnect.': 'Người chơi khác tái kết nối.',
    'is connecting to you.': 'đang kết nối tới bạn.',
    'Join a private game': 'Tham gia game riêng',
    'Joystick Simulation': 'Giả lập điều khiển',
    'Keyboard to Joystick': 'Giả lập điều khiển',
    'Language': 'Ngôn Ngữ',
    'Nickname': 'Tên',
    'No games available': 'Không có game nào',
    'Ok': 'Ok',
    'Retry': 'Thử lại',
    'Passcode to join your private game': 'Mật mã để tham gia game riêng của bạn.',
    'Play with anyone': 'Chơi với bất kỳ ai',
    'Reconnect': 'Tái kết nối',
    'Reset to Default': 'Cài đặt mặc định',
    'Singleplayer': 'Chơi một mình',
    'Multiplayer': 'Chơi hai người qua mạng',
    'Server is finding or creating a game.': 'Máy chủ tang tìm game.',
    'Settings': 'Cài Đặt',
    'The connection to server has just dropped.': 'Kết nối tới máy chủ bị rớt.',
    'The connection to the other player has just dropped.': 'Kết nối tới người chơi khác bị rớt.',
    'The other player has abandoned the game.': 'Người chơi khác đã rời bỏ game.',
    'to connect to Server': 'kết nối tới máy chủ',
    'to player': 'tới người chơi',
    'to Server': 'tới máy chủ',
    'Please enter the correct one.': 'Xin nhập lại mã chĩnh xác.',
    'Your nickname is required in multiplayer online game.': 'Bạn cần tên để tham gia chơi hai người trên mạng.',
    'Waiting': 'Chờ đợi',
    'Click on any joystick button, or': 'Click chuột lên bất kỳ nút nào trên tay điều khiển, hoặc',
    'press TAB key, then': 'ấn phím TAB trên bàn phím, sau đó',
    'press your intended key on the keyboard': 'ấn phím trên bàn phím',
    'in order to modify the mapping.': 'để thay đổi cài đặt bàn phím.',
};